config/routes.rb
Rails.application.routes.draw do
  

  resources :topics

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }


  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  resources :blogs do
    member do
      get :toggle_status
    end
    resources :comments
  end

  root to: 'pages#home'
end

app/models/blog.rb
class Blog < ApplicationRecord
  mount_uploaders :images, ImagesUploader
  mount_uploader :audio, AudioUploader
  enum status: { draft: 0, published: 1 }
  extend FriendlyId
  friendly_id :permalink, use: [:slugged, :history]
  validates :permalink, presence: true, uniqueness: true
  validates_presence_of :title, :body, :topic_id

  belongs_to :topic
  belongs_to :user
  has_many :comments, dependent: :destroy


  def self.special_blogs
    all
  end

  def self.featured_blogs
    limit(2)
  end

  def self.recent
    order("created_at DESC")
  end

  def should_generate_new_friendly_id?
       permalink_changed?
  end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :toggle_status]
  before_action :set_sidebar_topics, except: [:update, :destroy, :toggle_status]
  layout "blog"
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit, :toggle_status]}, site_admin: :all

  # GET /blogs
  # GET /blogs.json
  def index
    if logged_in?(:site_admin)
      @blogs = Blog.recent.page(params[:page]).per(5)
    else
      @blogs = Blog.published.recent.page(params[:page]).per(5)
    end
    @page_title = "IC-MN Blog"
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show

    if request.path != blog_path(@blog)

      return redirect_to @blog, :status => :moved_permanently

    end

    if logged_in?(:site_admin) || @blog.published?
      @blog = Blog.includes(:comments).friendly.find(params[:id])
      @comment = Comment.new

      @page_title = @blog.title 
      @seo_keywords = @blog.permalink
   
    else
      redirect_to blogs_path, notice: "Sie haben keine Zugang zu dieser Seite"
    end
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    user = current_user
    @blog = user.blogs.build(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Der Blog ist jetzt live.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Der Blog wurde erfolgreich gespeichert.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog gelöscht.' }
      format.json { head :no_content }
    end
  end

  def toggle_status
    if @blog.draft?
      @blog.published!
    elsif @blog.published?
      @blog.draft!
    end
        
    redirect_to blogs_url, notice: 'Blog wurde aktualisiert.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body, :topic_id, :status, :permalink, :audio, {images: []})
    end

    def set_sidebar_topics
      @side_bar_topics = Topic.with_blogs
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def gravatar_helper user
    image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}", width: 60
  end

  class CodeRayify < Redcarpet::Render::HTML
    def block_code(code, language)
      CodeRay.scan(code, language).div
    end
  end

  def markdown(text)
    coderayified = CodeRayify.new(filter_html: true, hard_wrap: true)

    options = {
      fenced_code_blocks: true,
      no_intra_emphasis: true,
      autolink: true,
      lax_html_blocks: true,
    }

    markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
    markdown_to_html.render(text).html_safe
  end

  def blog_status_color blog
    'color: red;' if blog.draft?
  end
end

app/views/blogs/_admin_actions.html.erb
<% if logged_in?(:site_admin) %>
  <nav class="blogcrumb">
    <%= link_to fa_icon('file-text'), toggle_status_blog_path(blog), style: blog_status_color(blog) %>
    <%= link_to fa_icon('pencil-square-o'), edit_blog_path(blog) %>
    <%= link_to fa_icon('trash'), blog, method: :delete, data: { confirm: 'Willst du das wirklich löschen?' } %>
  </nav>
<% end %>

app/views/blogs/_blog.html.erb
<div class="blog-post blog-body">
  <h2 class="blog-post-title"><%= link_to blog.title, blog %></h2> 
  <p class="blog-post-meta">Veröffentlicht <%= distance_of_time_in_words(blog.created_at, Time.now) %> | <%= blog.user.name %> </p>

  <nav class="breadcrumb">
    <%= render partial: 'blogs/admin_actions', locals: { blog: blog } %> 
  </nav>

  <% if  blog.audio.present? %>
    <audio controls>
    <source src="<%= blog.audio.url %>" type="audio/mpeg">Audio 2</audio><br>

  <% end %>


  <p> 
  <% if blog.images.present? %>
  <%= image_tag blog.images[0].url(:large).to_s, class: "img-fluid" %>
  <% end %>
    <%= truncate(markdown(blog.body), length: 600, escape: false) %> 
    <%= link_to "Weiterlesen", blog %> 
  </p>
</div>

app/views/blogs/_blog_breadcrumb.html.erb
  <nav class="breadcrumb">
    <%= link_to "Startseite", root_path, class: 'breadcrumb-item' %>
    <%= link_to @blog.topic.title, topic_path(@blog.topic), class: 'breadcrumb-item' %>

    <span class="breadcrumb-item active"><%= @blog.title %></span>

    <span class="pull-right">
      <%= render partial: 'blogs/admin_actions', locals: { blog: @blog } %>
    </span>
  </nav>

app/views/blogs/_display_images.html.erb
<div>
  <% @blog.images.each do |image| %>

    <%= image_tag image.url(:thumb).to_s %> 

  <% end %>

</div>

app/views/blogs/_form.html.erb
<%= form_for(blog) do |f| %>
  <% if blog.errors.any? %>
    <% blog.errors.full_messages.each do |error| %>
      <%= alert_generator error %>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= f.label :titel %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Titel" %>
  </div>

  <div class="form-group">
    <%= f.label :fünf_schlagworte_für_link_und_seo %>
    <%= f.text_field :permalink, class: 'form-control', placeholder: "Permalink mit wenigen Schlagworten (Keywords)" %>
  </div>


  <div class="form-group">
    <%= f.label :thema %>
    <%= f.collection_select(:topic_id, Topic.all, :id, :title,
                              {
                                include_blank: true
                              },
                              class: 'form-control'
                            )
    %>
  </div>

  <div class="form-group">
    <%= f.radio_button :status, 'draft' %>
    <%= f.label :status, 'Entwurf' %>

    <%= f.radio_button :status, 'published' %>
    <%= f.label :status, 'Veröffentlicht' %>
  </div>

  <div class="form-group">
    <%= f.label :textfeld %>
    <%= f.text_area :body, class: 'form-control', rows: 15, placeholder: "Kommentar" %>
  </div>

  <div class="form-group">
   <label class="btn btn-primary">
   Upload Audio (mp3)
   <%= f.file_field :audio, style: 'display:none;' %>
   </label>
   <label class="btn btn-primary">
   Upload Foto(s)
   <%= f.file_field :images, multiple: true, style: 'display:none;' %>
   </label>
  </div>

  <%= render 'display_images' %>

  <div class="form-group">
    <%= f.submit "Speichern", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<div class="col-sm-8 blog-main">

  <h1>Blog bearbeiten</h1>

  <%= render 'form', blog: @blog %>

  <%= link_to 'Anzeigen', @blog %> |
  <%= link_to 'Zurück', blogs_path %>

</div>

app/views/blogs/index.html.erb
<div class="col-sm-8 blog-main">

    <P><%= paginate @blogs , theme: 'twitter-bootstrap-4', pagination_class: "pagination-sm"  %></P>
    
    <%= render @blogs %>

    <P><%= paginate @blogs , theme: 'twitter-bootstrap-4', pagination_class: "pagination-sm"  %></P>

</div>

app/views/blogs/new.html.erb
<div class="col-sm-8 blog-main">
  <h1>Neuer Blogbeitrag</h1>

  <%= render 'form', blog: @blog %>

  <%= link_to 'Zurück', blogs_path %>
</div>

app/views/blogs/show.html.erb
<div class="col-sm-8 blog-main">

  <h2><%= @blog.title %></h2>

  <%= render 'blog_breadcrumb' %>


  <% if  @blog.audio.present? %>
    <audio controls>

    <source src="<%= @blog.audio.url %>" type="audio/mpeg">Audio</audio><br>

  <% end %>
  

  <div class="blog-body">
    <%= markdown @blog.body %>
  </div>


  

  <% @blog.images.each do |image| %>

   
    <%= image_tag image.url(:large).to_s %> 


  <% end %>




  <%= render 'comments/comment_form' %>

  <div id="comments" data-blog-id="<%= @blog.id %>">
    <%= render @blog.comments %>
  </div>

  
</div>