config/routes.rb
Rails.application.routes.draw do
  

  resources :topics

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }


  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  resources :blogs do
    member do
      get :toggle_status
    end
    resources :comments
  end

  root to: 'pages#home'
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates_presence_of :title, uniqueness: true

  has_many :blogs

  def self.with_blogs
    includes(:blogs).where.not(blogs: { id: nil })
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_sidebar_topics
  layout 'blog'

  def index
    @topics = Topic.all
  end

  def new

    @topic = Topic.new

  end

  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to blogs_path, notice: 'Das Thema ist gespeichert' }
      else
        format.html { render :new }
      end
    end
  end

  def show
    @topic = Topic.find(params[:id])

    if logged_in?(:site_admin)
      @blogs = @topic.blogs.recent.page(params[:page]).per(5)
    else
      @blogs = @topic.blogs.published.recent.page(params[:page]).per(5)
    end
  end

  private

  def topic_params
      params.require(:topic).permit(:title)
    end

  def set_sidebar_topics
    @side_bar_topics = Topic.with_blogs
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for(topic) do |f| %>
  <% if topic.errors.any? %>
    <% topic.errors.full_messages.each do |error| %>
      <%= alert_generator error %>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= f.text_field :title, class: 'form-control', placeholder: "Thema" %>
  </div>

  <div class="form-group">
    <%= f.submit "Speichern", class: 'btn btn-primary' %>
  </div>

  <% end %>

app/views/topics/_topic.html.erb
<div class='card col-md-5'>
  <%= link_to topic.title, topic_path(topic) %>
</div>

app/views/topics/index.html.erb
<div class="col-sm-8 blog-main">

  <h1>Themen</h1>
  
  <div class='topic-index row'>
    <%= render @topics %>
  </div>

  <hr>

  <div class='btn btn-secondary'>
    <%= link_to "Neues Thema", new_topic_path %>
  </div>
</div>

app/views/topics/new.html.erb
<div class="col-sm-8 blog-main">
  <h1>Neues Thema</h1>

  <%= render 'form', topic: @topic %>

  <%= link_to 'Zurück', blogs_path %>
</div>

app/views/topics/show.html.erb
<div class="col-sm-8 blog-main">

  <h1><%= @topic.title %></h1>

  <%= paginate @blogs %>
  
  <%= render @blogs %>

  <%= paginate @blogs %>

</div>