config/routes.rb
Rails.application.routes.draw do
  

  resources :topics

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }


  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  resources :blogs do
    member do
      get :toggle_status
    end
    resources :comments
  end

  root to: 'pages#home'
end

app/views/shared/_application_footer.html.erb
<div class="mastfoot">
  <div class="inner">
    <p class="app-footer"><%= copyright_generator %></p>
  </div>
</div>

app/views/shared/_application_nav.html.erb
<div class="masthead clearfix">
  <div class="inner">
    <h3 class="masthead-brand"><%= fa_icon('globe') %> IC-MN</h3>
    <nav class="nav nav-masthead app-nav">
      <%= nav_helper 'nav-link', 'span' %>
      <%= login_helper 'nav-link' %>
    </nav>
  </div>
</div>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p> 
    <%= copyright_generator %>
  </p>
  <p>
    <a href="#">zurück nach oben</a>
  </p>
</footer>

app/views/shared/_blog_masthead.html.erb
<div class="blog-header">
  <div class="container">
    <h1 class="blog-title">Zwischengedanken</h1>
    <p class="lead blog-description">Eindrücke von unseren Reisen und vom zuhause bleiben</p>
    <span>
      <%= link_to 'Blog schreiben /', new_blog_path if logged_in?(:site_admin) %>
    </span>
    <span>
      <%= link_to "Themen", topics_path %>
    </span>

    
  </div>
</div>

app/views/shared/_blog_nav.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded blog-nav">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="container">
    <%= link_to fa_icon('globe') + " IC-MN", root_path, class: 'navbar-brand' %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <%= nav_helper 'nav-link', 'li' %>  
        <%= login_helper 'nav-link' %>  
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_blog_sidebar.html.erb
<div class="col-sm-3 offset-sm-1 blog-sidebar">
  <div class="sidebar-module sidebar-module-inset">
    <h4>Über uns</h4>
    <p>
      Journalismus ist für uns eine Leidenschaft. Wir sind aber auch sonst sehr aktiv.
    </p>
    <p>
      Mit der Bigent gUG haben wir ein Sozialunternehmen gegründet, das Bildung, Gesundheit und Entwicklung fördert. <a href='https://www.bigent.org'>www.bigent.org</a>
    </p>
    <p> 
      Ausserdem haben wir eine Suchmaschine gebaut, die ihre  Gewinne in soziale Projekte investiert. Sie können uns helfen, indem Sie mit <a href='https://www.many4one.org'>many4one.org</a> suchen. Wir spenden!
    </p>
  </div>

  <%= source_helper("alert alert-info blog-sidebar-source") %>

  <div class="sidebar-module">
    <h4>Themen</h4>
    <% if @side_bar_topics.present? %>
      <% @side_bar_topics.each do |topic| %>
        <p><%= link_to topic.title, topic_path(topic) %></p>
      <% end %>
    <% end %>
  </div>

  <div class="sidebar-module">
    <h4>Wo wir sonst noch sind</h4>
    <ol class="list-unstyled social-links">
      <li><a href="https://www.linkedin.com/in/jutta-schwengsbier-a0281714/"><%= fa_icon "linkedin" %></a></li>
      <li><a href="https://www.facebook.com/search/top/?q=mirko%20schwanitz"><%= fa_icon "facebook-f" %></a></li>
      
    </ol>
  </div>
</div>

app/views/shared/_nav.html.erb
<div class="<%= location %>">
  <div><%= link_to "Home", root_path %></div>
  <div><%= link_to "Über uns", about_me_path %></div>
  <div><%= link_to "Kontakt", contact_path %></div>
  <div><%= link_to "Blog", blogs_path %></div>
  <div><%= link_to "Unser Team", portfolios_path %></div>
</div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <%= link_to "Alle Team Mitglieder ansehen", portfolios_path %> / 
      <a href="#">Zurück nach oben</a>
    </p>
    <p>
      <%= copyright_generator %>
    </p>
  </div>
</footer>

app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">IC-MN Team </h1>
    <p class="lead text-muted">Ob Künstlerporträt oder Wissenschaftsthemen, große Wirtschaftsfeature oder kleine Hörspiele. Wir haben für alle Ihre Wünsche ein offenes Ohr und produzieren unsere Beiträge in der Regel selbst. Rufen sie uns einfach an. Wir freuen uns.  </p>
    <p>
      <%= link_to 'Mehr über uns', about_me_path, class: 'btn btn-primary' %>
      <%= link_to 'Unser Blog', blogs_path, class: 'btn btn-secondary' %>
      <%= link_to 'Kontakt', contact_path, class: 'btn btn-success' %>
    </p>
  </div>
</section>

app/views/shared/_portfolio_nav.html.erb
<div class="collapse bg-inverse" id="navbarHeader">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 py-4">
        <h4 class="text-white">Über uns</h4>
        <p class="text-muted">Wir sind kein Journalisten Büro sondern ein Netzwerk freier Radioautorinnen, die auf internationale Berichterstattung spezialisiert sind. Natürlich können wir aber auch Filme machen oder online Berichte und Zeitungsartikel schreiben. Mit oder ohne Fotos. Sprechen Sie uns einfach an.</p>
      </div>
      <div class="col-sm-4 py-4">
        <h4 class="text-white">Zum Ansehen</h4>
        <ul class="list-unstyled">
          <%= nav_helper 'text-white', 'li' %>
          <li><%= login_helper 'text-white' %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="navbar navbar-inverse bg-inverse">
  <div class="container d-flex justify-content-between">
    <%= link_to "IC-MN", root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</div>